// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/LoginProto.proto

#ifndef PROTOBUF_proto_2fLoginProto_2eproto__INCLUDED
#define PROTOBUF_proto_2fLoginProto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace LoginProto {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_proto_2fLoginProto_2eproto();
void protobuf_AssignDesc_proto_2fLoginProto_2eproto();
void protobuf_ShutdownFile_proto_2fLoginProto_2eproto();

class Result;

// ===================================================================

class Result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:LoginProto.Result) */ {
 public:
  Result();
  virtual ~Result();

  Result(const Result& from);

  inline Result& operator=(const Result& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Result& default_instance();

  void Swap(Result* other);

  // implements Message ----------------------------------------------

  inline Result* New() const { return New(NULL); }

  Result* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Result& from);
  void MergeFrom(const Result& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 dwID = 1;
  void clear_dwid();
  static const int kDwIDFieldNumber = 1;
  ::google::protobuf::uint32 dwid() const;
  void set_dwid(::google::protobuf::uint32 value);

  // optional bool result = 2;
  void clear_result();
  static const int kResultFieldNumber = 2;
  bool result() const;
  void set_result(bool value);

  // @@protoc_insertion_point(class_scope:LoginProto.Result)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint32 dwid_;
  bool result_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_proto_2fLoginProto_2eproto();
  friend void protobuf_AssignDesc_proto_2fLoginProto_2eproto();
  friend void protobuf_ShutdownFile_proto_2fLoginProto_2eproto();

  void InitAsDefaultInstance();
  static Result* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Result

// optional uint32 dwID = 1;
inline void Result::clear_dwid() {
  dwid_ = 0u;
}
inline ::google::protobuf::uint32 Result::dwid() const {
  // @@protoc_insertion_point(field_get:LoginProto.Result.dwID)
  return dwid_;
}
inline void Result::set_dwid(::google::protobuf::uint32 value) {
  
  dwid_ = value;
  // @@protoc_insertion_point(field_set:LoginProto.Result.dwID)
}

// optional bool result = 2;
inline void Result::clear_result() {
  result_ = false;
}
inline bool Result::result() const {
  // @@protoc_insertion_point(field_get:LoginProto.Result.result)
  return result_;
}
inline void Result::set_result(bool value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:LoginProto.Result.result)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace LoginProto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_proto_2fLoginProto_2eproto__INCLUDED
